### ISSUE TITLE
Pre-Launch Checklist.

### ISSUE THREAD

**Issue by simplegridco** [simplegridco/simplegridco.github.io#1]
#### ℹ️  This ticket is opened to track all the work done before launch. I will document all the stuff that went before the launch of this ticket.
---
Next course of actions are:
### 1. Domain & Hosting 🌏 
- [x] Buy domain
- [x] Buy email
- [x] Set up hosting
- [x] Set up SSL using cloudflare free option

### 2. Social Media 🍸 
- [x] Facebook
- [x] Twitter
- [x] Instagram 
- [x] Pinterest
- [x] Quora
- [x] Github
- [x] Medium
- [x] Mailchimp
- [x] Designer News
- [ ] Youtube
- [x] Buffer
- [x] Join [Triberr](https://triberr.com/)

### 3. Analytics & SEO 📈 
- [x] Google Analytics
- [ ] Mixpanel
- [ ] Write title and description for website
- [ ] Design `og:image` for website

### 4. Brand & Styleguide 🎨 
- [x] Design logo
- [x] Finalize color palette
- [x] Design cover image

**Comment by simplegridco** [comment]
### 1. Domain & Hosting

I bought the domain name [simplegrid.co](http://simplegrid.co/) from godaddy with email facilities. 
It cost me  [Rs. 5046.32](https://github.com/simplegridco/simplegridco.github.io/issues/2#issuecomment-322060077) 

For hosting I have decided to go with [Publii](https://getpublii.com/). It is a open source CMS platform for static websites. As I have hosted the website on github, I have cut down the cost of hosting for the beginning. If the website gets picked up, I will move it to more private space.

Moved default nameservers to cloudflare ones for SSL. Now the website will be https://simplegrid.co [#3] 
[Tutorial for setting up custom & SSL for github hosted website](https://jwillmer.de/blog/tutorial/setup-custom-domain-and-ssl-for-github-hosted-website)

Having SSL moves you up in the google search list as google rewards website with https.

![alt-image](https://media.giphy.com/media/d3mlE7uhX8KFgEmY/giphy.gif)

**Comment by simplegridco** [comment]
### 2. Social Media

I have checked off all the accounts created. Posting all the links here.
- [Facebook](https://www.facebook.com/Simplegrid-966504526822381/?fref=ts)
- [Twitter](https://twitter.com/simplegridco)
- [Instagram](https://www.instagram.com/simplegridco/)
- [Pinterest](https://pinterest.com/simplegridco/)
- [Quora](https://www.quora.com/profile/Simplegridco)
- [Github](https://github.com/simplegridco)
- [Medium](https://medium.com/@simplegridco)

**Comment by simplegridco** [comment]
### 4. Brand & Styleguide 

![facebook-cover](https://user-images.githubusercontent.com/30976575/29280654-b4f1d8e6-8139-11e7-985f-b1d614433f20.png)
![logo-rectangle](https://user-images.githubusercontent.com/30976575/29280653-b4f17a40-8139-11e7-8ab7-84f6ca9dfee9.png)
![logo-square](https://user-images.githubusercontent.com/30976575/29280655-b4fce452-8139-11e7-87ca-e3220a786da0.png)
